name: Update pnpm-lock.yaml

on:
  push:
    branches:
      - main  # You can specify the branch you are working on

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use your Node.js version
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies and update lockfile
        run: pnpm install
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add pnpm-lock.yaml
          git commit -m "Update pnpm-lock.yaml to match package.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
